- .github/workflows/test.yml
- Makefile
- plugins/module_utils/vmware.py
- plugins/modules/vm_vm_drs_rule.py
- tests/integration/inventory
- tests/integration/targets/init.sh
- tests/integration/targets/prepare_vcsim/tasks/main.yml
- tests/integration/targets/vars.yml
- tests/integration/targets/vm_vm_drs_rule/run.yml
- tests/integration/targets/vm_vm_drs_rule/runme.sh
- tests/integration/targets/vm_vm_drs_rule/tasks/main.yml
- tests/unit/plugins/modules/test_vm_vm_drs_rule.py
- tests/unit/requirements.txt
> Add vm_vm_drs_rule module

- plugins/module_utils/vmware.py
- plugins/modules/cluster_ha.py
- tests/unit/plugins/modules/test_vm_vm_drs_rule.py
Fix some PEP8 issues
plugins/module_utils/vmware.py
cluster_ha
tests/unit/plugins/modules/test_vm_vm_drs_rule.py
#5
> Fix some PEP8 issues

- plugins/doc_fragments/vmware.py
- plugins/module_utils/vmware.py
- plugins/modules/cluster.py
- plugins/modules/cluster_drs.py
- plugins/modules/cluster_ha.py
- plugins/modules/vm_vm_drs_rule.py
- tests/integration/targets/cluster/playbook.yml
- tests/unit/plugins/modules/common/utils.py
The unit tests look better now, but there are still problems with the sanity tests. It looks like the doc fragment is missing.
This won't fix the sanity tests, I think we'll see some new issues once this is merged. But one thing at a time.
cluster
cluster_drs
cluster_ha
vm_vm_drs_rule
plugins/module_utils/vmware.py
tests/integration/targets/cluster/playbook.yml
tests/unit/plugins/modules/common/utils.py
#5
> Fix CI sanity tests

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/001-release-100.yaml
> Release 1.0.0

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/16-vm_list_group_by_clusters.yml
- galaxy.yml
- plugins/modules/vm_list_group_by_clusters.py
> Release v1.1.0

- changelogs/fragments/34-docs.yml
- plugins/modules/vcsa_settings.py
Fix the version_added doc for vcsa_settings module since it was released in v1.2.0
vcsa_settings
> Fix version added for module vcsa_settings

- docs/docsite/links.yml
Provide links for docsite.
docs/docsite/links.yml
Please tell me what I should document in the `communication` section. This is still missing.
> Provide links for docsite

- changelogs/fragments/35-add-requirements-filed-to-modules-doc.yml
- plugins/modules/appliance_info.py
- plugins/modules/guest_info.py
- plugins/modules/license_info.py
- plugins/modules/vcsa_settings.py
- plugins/modules/vm_list_group_by_clusters_info.py
Add requirements filed to modules documentation.
> Add requirements field to modules doc

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/23-new-module-content-create-template.yml
- changelogs/fragments/34-docs.yml
- changelogs/fragments/35-add-requirements-filed-to-modules-doc.yml
- changelogs/fragments/37-vm_list_group_by_clusters_info_returned_obj.yml
- galaxy.yml
create a new release 1.3.0
```paste below
```
> Release 1.3.0

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/10-rename_get_vm_by_name.yaml
- changelogs/fragments/48-add_folder_template.yml
- changelogs/fragments/49-add_vm_portgroup_info.yml
- changelogs/fragments/50-add_cluster_drs_module.yaml
- changelogs/fragments/51-migrate_vm_info_modules.yml
- changelogs/fragments/54-bugfix_custom_fact_values.yml
- changelogs/fragments/55-add_docs_for_mandatory_vars.yml
- galaxy.yml
Create release 1.4.0
- Release
> release 1.4.0

- README.md
- changelogs/fragments/61-update-readme-format.yaml
Updating README format to match standard template described here https://access.redhat.com/articles/7068606
README.md
> update readme format

- tests/integration/targets/group_vars.yml
- tests/integration/targets/vmware_cluster_vcls/defaults/main.yml
- tests/integration/targets/vmware_content_template/defaults/main.yml
Fixed integration tests datastore names
> Fixed datastore naming issues

- README.md
- changelogs/fragments/66-fix-typos-in-readme.yaml
> fixing typos

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/59-add-action_groups.yaml
- changelogs/fragments/60-add-cluster-module.yaml
- changelogs/fragments/61-add-cluster_vcls.yaml
- changelogs/fragments/61-update-readme-format.yaml
- changelogs/fragments/63-add-cluster-module-to-action_groups.yaml
- changelogs/fragments/64-add-cluster-module.yaml
- changelogs/fragments/66-fix-typos-in-readme.yaml
- galaxy.yml
> release 1.5.0

- .pre-commit-config.yaml
- changelogs/fragments/69-fix-various-typos-in-docs.yml
- plugins/doc_fragments/vmware.py
- plugins/doc_fragments/vmware_rest_client.py
- plugins/module_utils/_vmware.py
- plugins/module_utils/_vmware_rest_client.py
- plugins/modules/cluster.py
- plugins/modules/cluster_vcls.py
- plugins/modules/folder_template_from_vm.py
- plugins/modules/guest_info.py
- plugins/modules/vcsa_settings.py
- tests/integration/targets/vmware_cluster_drs/tasks/main.yml
- tests/integration/targets/vmware_cluster_vcls/tasks/main.yml
Fixes typos in documentation.
Also added a pre-commit option to spell check the repo. The pre-commit hooks are optional, but should make it easier for regular contributors to catch these issues before they are released.
> add spell check pre-commit and fix typos

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/69-fix-various-typos-in-docs.yml
- changelogs/fragments/70-migrate-cluster-drs-recommendations.yml
- changelogs/fragments/71-migrate-cluster-dpm.yml
- changelogs/fragments/73-fix_drs_backwards_vmotion_rate.yml
- galaxy.yml
> release 1.6.0

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/80-migrate-cluster-info-module.yml
- changelogs/fragments/81-migrate-content-library-item-info.yml
- galaxy.yml
> release 1.7.0

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/88-standardize-pyvmomi-methods.yml
- changelogs/fragments/89-consolidate-arg-specs-and-docs.yml
- changelogs/fragments/91-add-esxi_host-inventory.yml
- changelogs/fragments/92-fix-reference-in-content-template.yml
- galaxy.yml
> release 1.8.0

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/101-fix-missing-lib-error.yml
- changelogs/fragments/93-bugfix-vm_name-required.yml
- changelogs/fragments/95-use-client-utils-in-modules.yml
- changelogs/fragments/96-add-vms-inventory-plugin.yml
- changelogs/fragments/98-fix-relative-links-in-readme.yml
- changelogs/fragments/99-migrate-esxi-maintenance-mode.yml
- galaxy.yml
> release 1.9.0

- changelogs/fragments/103-migrate-vmware_folder.yml
- meta/runtime.yml
- plugins/module_utils/_vmware_folder_paths.py
- plugins/modules/folder.py
- tests/integration/targets/vmware_folder/defaults/main.yml
- tests/integration/targets/vmware_folder/run.yml
- tests/integration/targets/vmware_folder/tasks/main.yml
- tests/integration/targets/vmware_folder/tasks/test.yml
- tests/integration/targets/vmware_folder/vars.yml
- tests/integration/targets/vmware_folder/vars/main.yml
- tests/unit/plugins/modules/common/vmware_object_mocks.py
- tests/unit/plugins/modules/test_folder.py
This is migrating the community.vmware.vmware_folder module to here. The functionality is the same but the inputs have changed slightly to allow for more flexible usage.
folder
> migrate community vmware_folder module to here

- codecov.yml
- tests/unit/plugins/modules/common/utils.py
- tests/unit/plugins/modules/common/vmware_object_mocks.py
Follow up to #115 , this is updating the codecov checks to hopefully be a little more useful. I think in the next milestone we can try making them required 
- Chore Pull Request
> update codecov config

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/103-migrate-vmware_folder.yml
- changelogs/fragments/104-migrate-cluster-ha.yml
- changelogs/fragments/105-add-event-counting-file.yml
- changelogs/fragments/108-migrate-deploy_content_library.yml
- changelogs/fragments/109-migrate-vmware_content_manager.yml
- changelogs/fragments/111-migrate-vmware_host.yml
- changelogs/fragments/113-add-deploy-folder-template-module.yml
- galaxy.yml
> release 1.10.0

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/121-fix-bugs-in-new-modules.yml
- galaxy.yml
release 1.10.1
Fixes bugs found in new modules in 1.10
> release 1.10.1

- .ansible-lint
- .gitignore
- changelogs/fragments/123-fix-galaxy-import-warnings.yml
- plugins/inventory/esxi_hosts.py
- plugins/inventory/vms.py
- plugins/modules/cluster_ha.py
- plugins/modules/cluster_info.py
- plugins/modules/folder.py
- tests/sanity/ignore-2.15.txt
- tests/sanity/ignore-2.16.txt
These changes fix some warnings this repo gets while importing the collection to Automation Hub, during the ansible-lint phase 
> fix ansible-lint warnings in galaxy import

- changelogs/fragments/127-add-maintainer-docs.yml
- docs/maintainer.md
Add document to help future maintainers
> add docs for maintainers

- changelogs/fragments/131-update-query-file.yml
- extensions/audit/event_query.yml
Updating the query file based on feedback from the AAP team. This parses ESXi hosts when possible and uses the moid/name as ID when possible instead of a concatenated string
> update query file based on aap feedback

- galaxy.yml
Fixes commented out documentation link in galaxy.yml
> fix galaxy doc link

- docs/maintainer.md
Fixes broken list formatting in docs
> fix list in maintainer docs

- changelogs/fragments/144-update-min-pyvmomi-version.yml
- requirements.txt
- tests/unit/requirements.txt
Fixes https://github.com/ansible-collections/vmware.vmware/issues/56
Updates the minimum pyvmomi sdk package version to 8.0.3.0.1
> update pyvmomi min to 8.0.3.0.1

- changelogs/fragments/156-better-error-message-for-scheduled-power.yml
- plugins/modules/vm_powerstate.py
Updating the error message when the user tries to scheduled a task in the past
vm_powerstate
> add better scheduled powerstate error message

- changelogs/fragments/157-add-vcsa-backup-schedule.yml
- extensions/audit/event_query.yml
- meta/runtime.yml
- plugins/modules/vcsa_backup_schedule.py
- plugins/modules/vcsa_backup_schedule_info.py
- tests/integration/targets/vmware_vcsa_backup_schedule/defaults/main.yml
- tests/integration/targets/vmware_vcsa_backup_schedule/run.yml
- tests/integration/targets/vmware_vcsa_backup_schedule/tasks/main.yml
- tests/unit/plugins/modules/test_vcsa_backup_schedule.py
- tests/unit/plugins/modules/test_vcsa_backup_schedule_info.py
Adds a module to manage vcenter appliance backup schedules. Also included a module to gather info about the backup schedules
vcsa_backup_schedule
vcsa_backup_schedule_info
> add vcsa backup schedule modules

- changelogs/fragments/163-test-fixes.yml
- tests/integration/targets/vmware_inventory_vms/files/test.vms.yml
- tests/integration/targets/vmware_inventory_vms/tasks/main.yml
- tests/integration/targets/vmware_vm_portgroup_info/defaults/main.yml
- tests/integration/targets/vmware_vm_portgroup_info/tasks/main.yml
Fixes broken tests. Things changed in the vcenter lab that caused these failures
integration tests
> update broken tests

- changelogs/fragments/160-add-queries-for-clusters.yml
- extensions/audit/event_query.yml
- meta/runtime.yml
- plugins/modules/cluster_dpm.py
- plugins/modules/cluster_drs.py
- plugins/modules/cluster_drs_recommendations.py
- plugins/modules/cluster_ha.py
- plugins/modules/cluster_vcls.py
- tests/unit/plugins/modules/test_cluster_vcls.py
Adds any missing queries and cluster related queries for indirect node counting.
Also fixes a missing module in the action groups.
cluster modules
event query file
> add cluster module queries

- changelogs/fragments/165-add-folder-to-guest-info.yml
- plugins/modules/guest_info.py
Add the folder param to guest info so users can select the vm to query by name and folder path.
guest_info
> add folder param to guest info

- extensions/audit/event_query.yml
AAP team requested we remove the guest info test query
> remove test query

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/126-migrate-vmware_guest_snapshot.yml
- changelogs/fragments/144-update-min-pyvmomi-version.yml
- changelogs/fragments/146-drop-ansible-215.yml
- changelogs/fragments/147-make-client-utils-public.yml
- changelogs/fragments/148-add-more-audit-queries.yml
- changelogs/fragments/150-stadardize-vm-search-content-template.yml
- changelogs/fragments/151-fix-datastore-cluster-lookup.yml
- changelogs/fragments/152-rename-private-module-utils.yml
- changelogs/fragments/153-warn-on-duplicate-names-in-inven.yml
- changelogs/fragments/156-better-error-message-for-scheduled-power.yml
- changelogs/fragments/157-add-vcsa-backup-schedule.yml
- changelogs/fragments/158-add-missing-props-to-inven.yml
- changelogs/fragments/159-throw-error-when-dc-is-required.yml
- changelogs/fragments/160-add-queries-for-clusters.yml
- changelogs/fragments/162-fix-cluster_ha-settings-diff.yml
- changelogs/fragments/163-test-fixes.yml
- changelogs/fragments/164-add_advanced_settings_module.yml
- changelogs/fragments/165-add-folder-to-guest-info.yml
- changelogs/fragments/166-fix-snapshot-outputs.yml
- galaxy.yml
- meta/runtime.yml
- plugins/modules/vm_list_group_by_clusters_info.py
Release 2.0.0
Includes the tombstoning of vm_list_group_by_clusters, since that could not be done in an earlier pull request: https://github.com/ansible-collections/vmware.vmware/issues/30
> release 2.0.0

- changelogs/fragments/177-add-inven-example.yml
- plugins/inventory/esxi_hosts.py
- plugins/inventory/vms.py
Fixes https://github.com/ansible-collections/vmware.vmware/issues/170
Adding more detailed examples about how you can create groups based on tags
inventory plugins
> add inven examples for grouping by tags

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/174-update-test-structs.yml
- changelogs/fragments/176-fix-cache-in-inventories.yml
- changelogs/fragments/177-add-inven-example.yml
- changelogs/fragments/181-cluster-ha-pdl-typo.yml
- changelogs/fragments/183-fix-datastore-cluster-deploy.yml
- changelogs/fragments/186-deploy-mods-datastore-optional.yml
- galaxy.yml
> release 2.0.1

- changelogs/fragments/194-fix-integration-tests.yml
- tests/integration/targets/vmware_esxi_connection/tasks/eco-vcenter.yml
- tests/integration/targets/vmware_esxi_host/tasks/eco-vcenter.yml
- tests/integration/targets/vmware_esxi_maintenance_mode/tasks/eco-vcenter.yml
- tests/integration/targets/vmware_import_content_library_ovf/tasks/eco-vcenter.yml
- tests/integration/targets/vmware_moid_from_path/tasks/test_datastore_moid.yml
- tests/integration/targets/vmware_moid_from_path/tasks/test_host_moid.yml
Fix some integration tests to work with ansible-core 2.19.
esxi_connection
esxi_host
esxi_maintenance_mode
vmware_import_content_library_ovf
#171
#188
> Fix integration tests

- tests/integration/requirements.txt
- tests/integration/targets/vmware_moid_from_path/tasks/test_folder_moid.yml
- tests/integration/targets/vmware_moid_from_path/tasks/test_network_moid.yml
- tests/integration/targets/vmware_moid_from_path/tasks/test_resource_pool_moid.yml
2.19 test fixes for the moid lookup plugin
tests/integration/moid_from_path
> moid lookup fixes for 219

- changelogs/fragments/197-fix-folder_template_from_vm-tests.yml
- tests/integration/requirements.txt
- tests/integration/targets/vmware_folder_template_from_vm/tasks/main.yml
Fixes the tests for vmware_folder_template_from_vm and 2.19
tests/integration/vmware_folder_template_from_vm
> fix vmware_folder_template_from_vm tests

- CODEOWNERS
- changelogs/fragments/191-add-lookup-plugins.yml
Noticed a missing changelog, adding it. Also updating the code owners
> missing changelog and code owners

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/191-add-lookup-plugins.yml
- changelogs/fragments/192-fix-advanced-settings-cluster-ha.yml
- changelogs/fragments/194-fix-integration-tests.yml
- changelogs/fragments/197-fix-folder_template_from_vm-tests.yml
- galaxy.yml
> release 2.1.0

- changelogs/fragments/linting.yml
- plugins/modules/vcsa_backup_schedule.py
- plugins/modules/vcsa_backup_schedule_info.py
- plugins/modules/vm_advanced_settings.py
- plugins/modules/vm_snapshot.py
Fixed ansible-lint issues. This includes correcting indentation and improving Boolean truthiness checks to align with best practices and linting standards.
No changes to functionality or logic. Purely formatting and syntax adjustments to resolve lint warnings.
Validated with ansible-lint to confirm a clean run after changes.
> Fix indentation in examples

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/202-add-cluster-ha-required-if.yml
- changelogs/fragments/206-fix-content-template-err.yml
- changelogs/fragments/209-always-manage-failover-hosts.yml
- changelogs/fragments/210-replace-deprecated-json-encoder.yml
- changelogs/fragments/linting.yml
- galaxy.yml
> release 2.2.0

- extensions/audit/event_query.yml
Adds an additional query for the guest info module
> add query for guest info

- plugins/module_utils/vm/parameter_handlers/_memory.py
- plugins/modules/_vm_stub.py
- tests/integration/targets/vmware_vm_stub/tasks/main.yml
- tests/integration/targets/vmware_vm_stub/tasks/mem_params_tests.yml
- tests/unit/plugins/module_utils/vm/parameter_handlers/test_memory.py
Add all memory params to vm module
vm_stub
> add all memory params to vm module
