ansible-collections/vmware.vmware

.github/workflows/ansible-test.yml
tests/config.yml

It looks like the CI runs sanity tests with ansible-core and [unsupported Python versions](https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix). There are a lot of other issues in the CI, but I think this at least a start to fix them.
.github/workflows/ansible-test.yml
tests/config.yml
#5

Drop unsupported Python from CI

---

galaxy.yml

Some things in the CI seem to break because this isn't `vmware.vmware` according to `galaxy.yml`. Additionally, I've added some tags and fixed some links.
galaxy.yml
#5

Fix galaxy.yml

---

changelogs/fragments/15-clarify-pyvmomi-requirement.yml
plugins/module_utils/vmware.py
requirements.txt

Some modules in [community.vmware](https://github.com/ansible-collections/community.vmware) require pyVmomi 6.7.1 or later. I think it would be easier to move those modules in the future to this collection (if we want to) if we already define this in `requirements.txt` now.
Additionally, `HAS_PYVMOMIJSON` is only used to test this and we could get rid of this because a) it's not used anywhere yet and b) wouldn't be needed if we define `pyVmomi>=6.7.1` in `requirements.txt`.
requirements.txt
ansible-collections/community.vmware#2071
[6.7.1](https://pypi.org/project/pyvmomi/6.7.1/) has been released 2018-10-23, 5 1/2 years ago.

Require pyVmomi 6.7.1

---

changelogs/fragments/21-doc.yml
plugins/modules/appliance_info.py
plugins/modules/guest_info.py
plugins/modules/license_info.py
plugins/modules/vm_list_group_by_clusters.py

Relates to my inclusion review in https://github.com/ansible-collections/ansible-inclusion/discussions/75#discussioncomment-9503956

Doc improvements

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/25-deprecated_module_vm_list_goup_by_clusters.yml
meta/runtime.yml

Deprecating the module vm_list_group_by_clusters since it will be replaced with vm_list_group_by_clusters_info in v2.0.0
Adding a deprecating 
Deprecating the module vm_list_group_by_clusters since it will be replaced with vm_list_group_by_clusters_info in v2.0.0 and since then we will have 2 modules. 
I used that [doc](https://docs.ansible.com/ansible/latest/dev_guide/module_lifecycle.html#changing-a-module-or-plugin-name-in-the-ansible-main-repository) in order to sign that module as deprecated

Deprecating the old module vm_list_group_by_clusters

---

changelogs/fragments/10_vcsa_settings_new_module.yml
plugins/module_utils/vmware_rest_client.py
plugins/modules/vcsa_settings.py
tests/integration/targets/vcsa_settings/mock.json
tests/integration/targets/vcsa_settings/run.yml
tests/integration/targets/vcsa_settings/runme.sh
tests/integration/targets/vcsa_settings/tasks/main.yml
tests/integration/targets/vcsa_settings/vars.yml

System module is used to Configure system settings of VMware appliance.

Add vcsa_settings module

---

changelogs/fragments/27-guest-info-vm-name-bug.yml
plugins/module_utils/vmware_rest_client.py
plugins/modules/guest_info.py

Fixes ACA-1564
This PR fixes an exception thrown when specifying a guest name in the guest_info module. The `VM.FilterSpec` function used to apply the name filter was incorrectly qualified.
Additionally, the return value from the `_get_vm` function can be None, a single dictionary, or a list of dictionaries. I added logic to catch non-iterable values and fix them so the following `for vm in vms` loop will not fail 
guest_info
```yaml
---
- hosts: localhost
gather_facts: false
tasks:
- name: Gather guest info
vmware.vmware.guest_info:
validate_certs: false
hostname: "{{ vcenter_hostname }}"
username: "{{ vcenter_username }}"
password: "{{ vcenter_password }}"
guest_name: foo
```
Before:
```bash
PLAY [localhost] …
```

fix guest info bug

---

changelogs/fragments/23-new-module-content-create-template.yml
plugins/module_utils/vmware_rest_client.py
plugins/modules/content_template.py
tests/integration/inventory
tests/integration/targets/content_template/mock.json
tests/integration/targets/content_template/run.yml
tests/integration/targets/content_template/runme.sh
tests/integration/targets/content_template/tasks/main.yml
tests/integration/targets/content_template/vars.yml

Module to create template in content library from virtual machine.

Add content_template module

---

tests/integration/targets/vmware_content_template/defaults/main.yml
tests/integration/targets/vmware_content_template/vars.yml
tests/integration/targets/vmware_vm_list_group_by_clusters_info/defaults/main.yml

In order to allow to run integration targets in parallel and avoid interference between them, we are adding `"{{ tiny_prefix }}"` to all VMware object's names that are created in integration tests. 
For each integration target the `tiny_prefix` variable will be populated with a uuid string that will be used as prefix for all VMware objects created in that specific target, thus ensuring that there will be no interference when executing in parallel the other integration targets.

Add tiny_prefix to vmware object's names in integration tests

---

CODEOWNERS

This PR adds the code owners file so that QE could see the pipelines run without manual intervention of devs.
The names will be unrecognized now, but after merging it should give the right permissions.

add qe reviewers

---

.github/workflows/eco-vcenter-ci.yaml
.gitignore
Makefile
tests/integration/generate_integration_config.sh
tests/integration/integration_config.yml.tpl
tests/integration/targets/init.sh
tests/integration/targets/runme.sh
tests/integration/targets/vmware_appliance_info/run.yml
tests/integration/targets/vmware_appliance_info/runme.sh
tests/integration/targets/vmware_content_template/run.yml
tests/integration/targets/vmware_content_template/runme.sh
tests/integration/targets/vmware_guest_info/run.yml
tests/integration/targets/vmware_guest_info/runme.sh
tests/integration/targets/vmware_guest_info/tasks/main.yml
tests/integration/targets/vmware_license_info/run.yml
tests/integration/targets/vmware_license_info/runme.sh
tests/integration/targets/vmware_vm_list_group_by_clusters_info/run.yml
tests/integration/targets/vmware_vm_list_group_by_clusters_info/runme.sh
tools/prepare_symlinks.yml

This is a PR for adding the action to run the integration tests on the eco vcenter installed on our baremetals. 
The changes are aligned with the validated content repo, and hold the same structure.
The changes includes additional var sent to the the ansible-playbook command called tiny_prefix -
this was added to be aligned the behaviour of the downstream CI, which runs the tests in parallel and requires this var.
eco-vcenter-ci.yml
The PR tested locally and from my own fork, you can see the successful result [here](https://github.com/shellymiron/vmware.vmware/actions/runs/9700098351/job/26770684753).
We will be able to see the job runs on main only after the PR will be merged. 
please review :) @anna-savina @elsapassaro

add vmware.vmware upstream CI

---

changelogs/fragments/10-rename_get_vm_by_name.yaml
plugins/module_utils/vmware_rest_client.py
plugins/modules/content_template.py

This method is used twice in VmwareRestClient class.

ACA-1650: Rename get_vm_by_name method

---

changelogs/fragments/48-add_folder_template.yml
plugins/doc_fragments/vmware.py
plugins/module_utils/vmware.py
plugins/module_utils/vmware_folder_paths.py
plugins/modules/folder_template_from_vm.py
tests/integration/targets/vmware_folder_template_from_vm/defaults/main.yml
tests/integration/targets/vmware_folder_template_from_vm/run.yml
tests/integration/targets/vmware_folder_template_from_vm/tasks/main.yml
tests/integration/targets/vmware_folder_template_from_vm/vars.yml

This module creates a template in a folder from a VM. Its designed to replace some of the functionality in community.vmware.vmware_guest.
The module allows a user to create or delete a template in a folder. If you create a template, you must specify a VM to clone and use as a base for the template. Once the template is created, the user would use another module to modify the configuration (right now I think they would use vmware_guest, but a new module would probably be useful).
This module is similar in functionality to the existing content_template module, which creates/deletes a template in a content library.
folder_template_from_vm

Mm feature/save vm as template

---

tests/integration/targets/vmware_folder_template_from_vm/defaults/main.yml
tests/integration/targets/vmware_folder_template_from_vm/tasks/main.yml
tests/integration/targets/vmware_folder_template_from_vm/tasks/verify_template_creation.yml
tests/integration/targets/vmware_folder_template_from_vm/tasks/verify_template_deletion.yml
tests/integration/targets/vmware_folder_template_from_vm/vars.yml

Extending integration tests for folder_template_from_vm module:
- Create templates from a VM both in the same VM folder and in a different folder
- Add assertions to check that the newly created guest is indeed marked as template
- Use the module itself to remove the template

Add checks in folder_template_from_vm tests

---

.github/workflows/ansible-test.yml
changelogs/fragments/51-migrate_vm_info_modules.yml
plugins/doc_fragments/vmware_rest_client.py
plugins/module_utils/vmware.py
plugins/module_utils/vmware_facts.py
plugins/module_utils/vmware_folder_paths.py
plugins/module_utils/vmware_rest_client.py
plugins/modules/guest_info.py
tests/integration/targets/prepare_combined_vcenter_simulator/files/default.conf
tests/integration/targets/prepare_combined_vcenter_simulator/files/entrypoint.sh
tests/integration/targets/prepare_combined_vcenter_simulator/tasks/main.yml
tests/integration/targets/prepare_combined_vcenter_simulator/vars/main.yml
tests/integration/targets/prepare_rest/defaults/main.yml
tests/integration/targets/prepare_rest/tasks/main.yml
tests/integration/targets/prepare_vcsim/defaults/main.yml
tests/integration/targets/prepare_vcsim/tasks/main.yml
tests/integration/targets/vmware_guest_info/run.yml
tests/integration/targets/vmware_guest_info/tasks/main.yml
tests/integration/targets/vmware_guest_info/vars.yml
tests/unit/plugins/modules/test_guest_info.py

This is an attempt to migrate vm info modules from community.vmware (vmware_guest_info, vmware_vm_info) into vmware.vmware. Since there is already a vm info module in vmware.vmware (guest_info), the functionality from the two community modules has been added to guest_info
This module also requires the rest and soap APIs. So for the simulator tests i added an API gateway so both APIs can be accessed on the same port.
All of the changes should be backwards compatible. We do plan on deprecating the module's old output and removing it at some point in the future. More on that in the additional info section.
guest_info
While the inputs for guest_info has not changed, the output should probably be changed. Theres some duplicated information, and some of the values …

migrating community vm info modules into guest_info

---

tests/integration/targets/vmware_folder_template_from_vm/tasks/main.yml

When running `vmware_folder_template_from_vm` integration test in Jenkins CI on real vcenter, the test is failing when trying to create the template with the following error:
```
Traceback (most recent call last):
File "/root/.ansible/tmp/ansible-tmp-1722237961.4638362-112-170133260483632/AnsiballZ_folder_template_from_vm.py", line 107, in <module>
_ansiballz_main()
File "/root/.ansible/tmp/ansible-tmp-1722237961.4638362-112-170133260483632/AnsiballZ_folder_template_from_vm.py", line 99, in _ansiballz_main
invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
File "/root/.ansible/tmp/ansible-tmp-1722237961.4638362-112-170133260483632/AnsiballZ_folder_template_from_vm.py", line 47, in invoke_module
runpy.run_module(mod_name='ansible_collections.vmware.vmware.plugins.modules.folder_template …
```

Fix folder_template_from_vm test failure

---

changelogs/fragments/59-add-action_groups.yaml
meta/runtime.yml

I think we should implement an action group since this can be quite useful. I guess sooner or later someone will open a feature request for this, anyway.
amazon.aws and community.aws seem to share the action group `aws`. I suggest the same here: community.vmware already uses `vmware`, so let's also use it here.
Additionally, we might consider renaming the action group of the modules in vmware.vmware_rest from `vmware_rest` to `vmware`, but this is off-topic here. Just wanted to mention it as an idea.
If you think it would be better to not share action groups between those collections, that's also fine for me. The important thing is to have one in order to allow people to use module defaults. If you think it would be better to have a unique name for the action group, it would be great if …

Add action_groups

---

changelogs/fragments/60-add-cluster-module.yaml
plugins/modules/cluster.py
tests/integration/targets/vmware_cluster/defaults/main.yml
tests/integration/targets/vmware_cluster/run.yml
tests/integration/targets/vmware_cluster/tasks/main.yml
tests/integration/targets/vmware_cluster/vars.yml
tests/integration/targets/vmware_vm_portgroup_info/tasks/main.yml
tests/unit/plugins/modules/test_cluster.py

This is a migration of the community.vmware.vmware_cluster module.
The inputs have remained the same (although more aliases are allowed for the `cluster` attribute).
Ive added identifying information about the cluster in the outputs. When a cluster is destroyed, only the name is returned. When a cluster is created (or already exists) the cluster name and moid are returned.
cluster

migrate community.vmware.vmware_cluster module

---

changelogs/fragments/64-add-cluster-module.yaml
plugins/modules/folder_template_from_vm.py

The `folder_template_from_vm` plugin was one of the first to be migrated from the community collection. It included a very simple method to wait for a running task in vmware. It looks like that method did not correctly evaluate the state of running tasks. This meant that running tasks would be marked as failures.
We now have a much better utility for waiting for running tasks. This change makes the plugin use that instead.
folder_template_from_vm

fix integration test failures for folder_template_from_vm

---

changelogs/fragments/63-add-cluster-module-to-action_groups.yaml
meta/runtime.yml

This is a follow-up to both #59 and #60 to add the `cluster` module to the `action_group`.
cluster
meta/runtime.yml
Since there hasn't been a release containing this module yet, I made this a trivial change. I don't think this needs to show up in the changelog. Let me know if you think otherwise and I'll change it.

Add cluster to action group

---

changelogs/fragments/61-add-cluster_vcls.yaml
meta/runtime.yml
plugins/modules/cluster_vcls.py
tests/integration/targets/vmware_cluster_vcls/defaults/main.yml
tests/integration/targets/vmware_cluster_vcls/run.yml
tests/integration/targets/vmware_cluster_vcls/tasks/main.yml
tests/integration/targets/vmware_cluster_vcls/vars.yml
tests/unit/plugins/modules/test_cluster_vcls.py

This is a migration of the community.vmware.vmware_cluster_vcls module.
The inputs are backwards compatible. I added two inputs, `datastores_to_add` and `datastores_to_remove` to allow incremental modifications to the vCLS config. The legacy module only allowed absolute modifications; you needed to specify all allowed datastores every time.
The outputs that return any datastores added or removed by the module have changed key names to be more consistent with other output names in this collection. For example, `Added_AllowedDatastores` -> `added_datastores` 
Ive also added a new output to return the entire list of allowed datastores, `allowed_datastores`.
cluster_vcl
Heres an example of the new output from the simulator tests:
```
{
"added_datastores": [ …
```

migrate community.vmware.vmware_cluster_vcls module

---

.github/workflows/ansible-sanity.yml

Now that ansible-core 2.18 is out, we should (actually: have to) run the sanity tests with this release.

Run sanity tests with ansible-core 2.18

---

changelogs/fragments/70-migrate-cluster-drs-recommendations.yml
meta/runtime.yml
plugins/modules/cluster_drs_recommendations.py
tests/integration/targets/vmware_cluster_drs_recommendations/defaults/main.yml
tests/integration/targets/vmware_cluster_drs_recommendations/run.yml
tests/integration/targets/vmware_cluster_drs_recommendations/tasks/main.yml

This migrates the cluster_drs_recommendations module from the community.vmware collection
The inputs have not changed.
The outputs have changed from the original module. This version reports a description of the applied recommendations as well as details about the vcenter task associated with the change
cluster_drs_recommendations

migrate cluster_drs_recommendations module

---

changelogs/fragments/73-fix_drs_backwards_vmotion_rate.yml
plugins/modules/cluster_drs.py
tests/integration/targets/vmware_cluster_drs/tasks/main.yml

Fixes https://github.com/ansible-collections/vmware.vmware/issues/68
When setting the DRS vmotion rate, the user input value gets reversed by the vCenter API (so 1 becomes 5 and 5 becomes 1). This is confusing because the UI and documentation do not indicate this in anyway.
This fix makes the module reverse the numbers in code, so if a user chooses a rate of 1, we change it to 5 in code before inputting it in the API. It will display as 1 in the UI which is what the user wanted in the first place.
cluster_drs
The `community.vmware.vcenter_cluster_info` module reports back what the API says. This means that if the user sets the DRS rate to 2, the cluster info module will say the DRS rate is 4. Obviously this is confusing, so when the info module is migrated to this …

Mm bugfix/drs threshold backwards

---

changelogs/fragments/75-fix-dpm-automation-level-terms.yml
plugins/modules/cluster_dpm.py

The automation level option for dpm_cluster did not match the options that are used in the UI. This is because the API uses a different word (automated vs automatic).
This change modifies the module options to match what the user sees in the vcenter UI and docs.
cluster_dpm

fix dpm automation level option

---

changelogs/fragments/74-fix-drs-recommendation-task-results.yml
changelogs/fragments/75-fix-dpm-automation-level-terms.yml

Those changelog fragments will turn up in the changelog. I wonder if this is really helpful. I mean, it's not really a change compared to the last version, is it? Those modules haven't been part of this release. This might confuse some people.
I don't have a strong opinion on this. Just merge this PR or close it if you want to keep those (future) changelog entries. Personally, I think there hasn't been a change compared to 1.5.0 so there shouldn't be any entries in the changelog, either.
cluster_drs_recommendations
cluster_dpm
#70
#71
#73
#74
#75
cc @mikemorency

Drop unnecessary changelog entries

---

changelogs/fragments/80-migrate-cluster-info-module.yml
meta/runtime.yml
plugins/module_utils/_vmware_facts.py
plugins/module_utils/_vmware_folder_paths.py
plugins/module_utils/_vmware_rest_client.py
plugins/modules/cluster_dpm.py
plugins/modules/cluster_drs.py
plugins/modules/cluster_info.py
tests/integration/targets/vmware_cluster_dpm/tasks/main.yml
tests/integration/targets/vmware_cluster_drs/tasks/main.yml
tests/integration/targets/vmware_cluster_info/defaults/main.yml
tests/integration/targets/vmware_cluster_info/run.yml
tests/integration/targets/vmware_cluster_info/tasks/main.yml
tests/integration/targets/vmware_cluster_info/vars.yml
tests/unit/plugins/modules/common/utils.py
tests/unit/plugins/modules/common/vmware_object_mocks.py
tests/unit/plugins/modules/test_cluster_info.py

This migrates the vmware_cluster_info module from the community.vmware collection to this collection.
The inputs are mostly the same. There is one input that was renamed to match the guest_info module (gather_tags).
The outputs are mostly the same. However, there are some changes worth noting:
- I added DPM facts in (they were previously not gathered)
- I fixed the output DPM and DRS rates so they match what is shown in the UI. Previously, the opposite value was shown
- I standardized the "enabled" outputs. Now the outputs are `<service>_enabled` where service could be `dpm`, `drs`, `ha`, etc
cluster_info

migrate cluster info module from community

---

changelogs/fragments/81-migrate-content-library-item-info.yml
meta/runtime.yml
plugins/module_utils/_vmware_rest_client.py
plugins/modules/content_library_item_info.py
plugins/modules/content_template.py
tests/integration/targets/vmware_content_library_item_info/defaults/main.yml
tests/integration/targets/vmware_content_library_item_info/run.yml
tests/integration/targets/vmware_content_library_item_info/tasks/main.yml
tests/integration/targets/vmware_content_library_item_info/vars.yml
tests/unit/plugins/modules/test_content_library_item_info.py

This is migrating the content_library_item_info from the vmware_rest collection to here. The auto-generated module in the rest collection does not work due to an issue with the OpenAPI spec, so its easier to add the functionality to this collection instead.
I also consolidated some of the content library shared methods in the rest api module_util
content_library_item_info

Mm feature/migrate content library item info

---

changelogs/fragments/83-fix-content-library-item-info-args.yml
plugins/modules/content_library_item_info.py

The library item name and id are ignored if library item id is provided. This is because the library item id is unique within a vcenter. This pr updates the documentation to reflect that and will stop the user from performing a nonsensical query
content_library_item_info

fix bug where inputs were silently ignored

---

changelogs/fragments/92-fix-reference-in-content-template.yml
plugins/modules/content_template.py
tests/integration/targets/vmware_content_template/tasks/main.yml

Fixes https://github.com/ansible-collections/vmware.vmware/issues/90
While refactoring the content_template module, one variable reference was missed. There are no tests for the spot that this issue occurred. I fixed the variable and added tests to cover this spot.
content_template

fix content_template library_id reference in delete

---

.github/workflows/ansible-test.yml

For `Ubuntu 24.04`  `podman=3.4.4+ds1-1ubuntu1` is not available
Also bug https://github.com/actions/runner-images/issues/7753 was fixed

Fixed podman version

---

changelogs/fragments/104-migrate-cluster-ha.yml
meta/runtime.yml
plugins/modules/cluster_ha.py
tests/integration/targets/vmware_cluster_ha/defaults/main.yml
tests/integration/targets/vmware_cluster_ha/run.yml
tests/integration/targets/vmware_cluster_ha/tasks/main.yml
tests/integration/targets/vmware_cluster_ha/vars.yml
tests/unit/plugins/modules/common/vmware_object_mocks.py
tests/unit/plugins/modules/test_cluster_ha.py

Migrating vmware_ha_cluster from community to here. The functionality should be the same, but the inputs and outputs are slightly different. Theres a ton of options in this module; I did my best trying to cover them in the test cases but I am not sure how to programmatically validate some of the functionality.
cluster_ha

migrate cluster_ha module from community

---

plugins/module_utils/_module_deploy_content_library_base.py

Fixes issue where an error is thrown if the user does not provide the option library_name parameter
New functionality will mean all libraries are searched if the name is not provided
deploy_content_library_ovf
deploy_content_library_template

fix deploy content modules when library name is not provided

---

.github/workflows/ansible-sanity.yml

Since the collection neither supports nor tests with those outdated ansible (core) versions, I think we should drop ubuntu-20.04 from GitHub workflow.
.github/workflows/ansible-sanity.yml
https://forum.ansible.com/t/40187
ansible-collections/community.vmware#2312

Drop ubuntu-20.04 from GitHub workflow

---

changelogs/fragments/132-add-explicit-client-params.yml
plugins/inventory_utils/_base.py
plugins/module_utils/_module_pyvmomi_base.py
plugins/module_utils/_module_rest_base.py
plugins/module_utils/clients/_pyvmomi.py
plugins/module_utils/clients/_rest.py
tests/unit/plugins/module_utils/clients/test_pyvmomi.py
tests/unit/plugins/module_utils/clients/test_rest.py
tests/unit/plugins/module_utils/test_module_pyvmomi_base.py
tests/unit/plugins/module_utils/test_module_rest_base.py

Testing the recommendation from https://github.com/ansible-collections/vmware.vmware/issues/133 and making client parameters explicit instead of relying on a dict
client/_pyvmomi

make pyvmomi client inputs explicit

---

changelogs/fragments/135-add-moid-to-inven-out.yml
plugins/inventory_utils/_base.py
tests/unit/plugins/inventory_utils/test_base.py

Always include the moid in the inventory plugin output. The MOID is used by other modules and reporting. Its also the only consistent unique identifier across all objects. We should always return it
vms inventory
esxi_hosts inventory

include moid in inven output

---

plugins/inventory/vms.py

The VM inventory is missing the actual method call to filter hosts out. This adds that in. There is another changelog that already captures this addition
vms inventory

missed adding host filtering to vm inventory

---

changelogs/fragments/138-add-ovf-upload-module.yml
meta/runtime.yml
plugins/modules/import_content_library_ovf.py
tests/integration/targets/vmware_content_library/defaults/main.yml
tests/integration/targets/vmware_import_content_library_ovf/defaults/main.yml
tests/integration/targets/vmware_import_content_library_ovf/run.yml
tests/integration/targets/vmware_import_content_library_ovf/tasks/eco-vcenter.yml
tests/integration/targets/vmware_import_content_library_ovf/tasks/main.yml
tests/integration/targets/vmware_import_content_library_ovf/vars.yml
tests/integration/targets/vmware_vm_powerstate/tasks/eco-vcenter.yml
tests/unit/plugins/modules/test_import_content_library_ovf.py

Adding a module to upload an OVF or OVA file from a remote source to a content library. The remote source can be the Ansible host filesystem, an HTTPS/HTTP URL, a file URL, or a datastore URL.
content_library_upload_ovf
Originally, this was going to be a migration of the community.vmware.deploy_ovf module. That allows a user to deploy an OVF from a remote source. However, that module is complex and has a lot of extra features that would be more difficult to maintain.
I decided to create a module supports existing use cases in vmware_ops and vmware_rest and try to decrease the scope.
FYI @mariolenz  at this point, this module cannot replace the `deploy_ovf` module and there I currently have no plan to migrate more functionality. But I do think many `deploy_ovf` …

adding module to upload ovf to content library

---

changelogs/fragments/151-fix-datastore-cluster-lookup.yml
plugins/module_utils/_module_pyvmomi_base.py
tests/unit/plugins/module_utils/test_module_pyvmomi_base.py

Fixes https://github.com/ansible-collections/vmware.vmware/issues/152
When looking up a datastore cluster by name or moid, the wrong folder was used if a datacenter was provided. This fixes that issue
_module_pyvmomi_base

fix datastore cluster lookups

---

changelogs/fragments/150-stadardize-vm-search-content-template.yml
plugins/modules/content_template.py
tests/integration/targets/vmware_content_template/run.yml
tests/integration/targets/vmware_content_template/vars.yml
tests/unit/plugins/modules/test_content_template.py

Adds standard VM search params to the content_template module (uuid, moid, name_match etc).
Also makes the module arg validation more accurate
content_template
All of the changes are backwards compatible

add vm search params to content_template

---

changelogs/fragments/153-warn-on-duplicate-names-in-inven.yml
plugins/inventory/esxi_hosts.py
plugins/inventory/vms.py
plugins/inventory_utils/_base.py
tests/unit/plugins/inventory_utils/test_base.py

Adds a warning/error if more than one host has the same inventory hostname in the inventory plugins.
Also moved a bunch of duplicate code from the esxi/vms plugins to the base plugin class
Previously, the plugins would just silently skip the duplicate hosts
vm and esxi inventory plugins

add warnings and errors for duplicate hosts in inventorys

---

changelogs/fragments/158-add-missing-props-to-inven.yml
plugins/inventory/esxi_hosts.py
plugins/inventory/vms.py

When a user has the default keyed_groups values for the vm inventory, it is easy to accidentally not collect required config properties. Although we do warn users about making sure the required props are collected if they change settings, this seems like an easy issue to fall into without really understanding why.
This change makes sure that we collect the parameters that are required for the default keyed_groups
vms inven
Also added some comments to help indicate why we make sure certain props are collected

fix required param issue for vm inven

---

changelogs/fragments/159-throw-error-when-dc-is-required.yml
plugins/module_utils/_folder_paths.py
tests/unit/plugins/module_utils/test_folder_paths.py

The `get_vms_using_params` method can cause a situation where the user provides a relative folder path without a datacenter name. This leads to an error.
In other situations, it could lead to a much slower search result or the wrong item being chosen. I do not know of an instance where it has happened yet though.
This change throws an error if the datacenter is not provided and the path does not look like its already absolute.
This is a major change, since it could possibly cause users to get errors where there were no errors before.
folder_paths

throw error when datacenter is missing from relative paths

---

changelogs/fragments/166-fix-snapshot-outputs.yml
plugins/modules/vm_snapshot.py
tests/integration/targets/vmware_vm_snapshot/tasks/main.yml
tests/unit/plugins/modules/test_vm_snapshot.py

This fixes an issue where the snapshot details were not included in every output. While testing I also found that removing snapshots when there are large snapshot trees did not work. I fixed that as well.
vm_snapshot

ensure snapshot output when state is present

---

plugins/modules/vcsa_backup_schedule_info.py

This changes the vcsa_backup_schedule_info outputs to better match vcsa_backup_schedule inputs
vcsa_backup_schedule_info
Since this is an unreleased module, I don't think a changelog is required

change schedule info output to match schedule inputs

---

changelogs/fragments/183-fix-datastore-cluster-deploy.yml
plugins/module_utils/_module_deploy_vm_base.py
plugins/module_utils/_module_pyvmomi_base.py
plugins/modules/deploy_content_library_ovf.py

Fixes https://github.com/ansible-collections/vmware.vmware/issues/152
This fixes deployments that use a datastore cluster by simplifying how we pick which DS is used. Now we select the datastore with the most space available. Previously we tried to use SDRS to select the best DS but the method requires so many inputs, it is not feasible to use it for these modules. See https://github.com/vmware/pyvmomi/issues/213
In the future we may want to re-add this method but right now it has no use and doesn't work so I removed it.
deploy_content_library_ovf

fix ds cluster deployments

---

changelogs/fragments/181-cluster-ha-pdl-typo.yml
plugins/modules/cluster_ha.py

Fixes https://github.com/ansible-collections/vmware.vmware/issues/179
There is a typo when using the PDL mode 'restart'. It causes the module to fail with an error
cluster_ha

fix typo in cluster ha pdl restart mode

---

changelogs/fragments/192-fix-advanced-settings-cluster-ha.yml
plugins/module_utils/_advanced_settings.py
plugins/module_utils/_vsphere_tasks.py
plugins/modules/cluster_drs.py
plugins/modules/cluster_ha.py
tests/integration/run_eco_vcenter_ci.sh
tests/integration/targets/vmware_cluster_ha/tasks/main.yml
tests/unit/plugins/module_utils/test_advanced_settings.py
tests/unit/plugins/modules/test_cluster_ha.py

Fixes https://github.com/ansible-collections/vmware.vmware/issues/190
When a user tries to specify a non-string value for cluster HA or DRS advanced settings, an error is thrown.
This error is vague and unhelpful for the HA module. DRS actually has a decent error, so I didnt modify that
This change converts all values to strings for those modules and also adds a better error message for the HA module.
cluster_ha
cluster_drs
Tests need https://github.com/ansible-collections/vmware.vmware/pull/191

cluster ha advanced setting bugfix

---

changelogs/fragments/206-fix-content-template-err.yml
plugins/modules/content_template.py

Replaces a non-existent method from the content_template module. This method is present in the community collection, where this module came from originally. But it no longer exists. It seems we have not hit this piece of code, until now.
I think the error _was_ being thrown because of an issue in the test lab, but it is no longer happening. I copied how other modules handle this error and used that in place of the bad method.
content_template

Fix non-existent method in content_template

---

changelogs/fragments/213_re-enable_pyvmomi-for-tests.yml
tests/integration/requirements.txt

I hope I've fixed the issues with pyvmomi 9 in community.vmware 5.7.1. So let's give it another try with pyvmomi 9 :-)

Re-enable pyvmomi 9.0 in tests

---

changelogs/fragments/232-remove-six-imports.yml
plugins/module_utils/_facts.py
plugins/module_utils/_vsphere_tasks.py

Removes types and methods imported from six, replacing them with python3 versions. This is to fix a sanity check coming from devel.
See https://github.com/ansible-collections/vmware.vmware/pull/230
module_utils/_facts.py
module_utils/_vsphere_tasks.py

remove six imports

---

changelogs/fragments/244-fix-cluster-ac-policy/244-fix-cluster-ac-policy.yml
plugins/modules/cluster_ha.py

If the cluster admission control (ac.) policy is set and then ac. is disabled, we want to reinstate the policy setting and enable ac.
See bug for details on how to reproduce.
Fixes: #243

fix: cluster admission control: set requested policy also when ac is disabled

---

changelogs/fragments/246-add-import-content-library-iso.yml
meta/runtime.yml
plugins/modules/import_content_library_iso.py
tests/integration/targets/vmware_import_content_library_iso/defaults/main.yml
tests/integration/targets/vmware_import_content_library_iso/meta/main.yml
tests/integration/targets/vmware_import_content_library_iso/tasks/eco-vcenter.yml
tests/integration/targets/vmware_import_content_library_iso/tasks/main.yml
tests/unit/plugins/modules/test_import_content_library_iso.py

Current modules only allow uploading of OVF or OVA images to content library.
This module allows user to upload or import ISO images to content library.
import_content_library_iso
Currently user can only import OVF or OVA images to content library using import_content_library_ovf,
I am using content library also for installer iso images and kickstart images.
This feature adds new module import_content_library_iso to allow uploading or importing of ISO images.
As this module is pretty much copy of import_content_library_ovf module,
it's debatable, should this be separate module or should import_content_library_ovf to be improved.
A new module with a lesser impact on old automations seems like a better option to me.

Add module for uploading ISO images to content library.

---

plugins/modules/tag_categories.py
tests/integration/targets/vmware_tags/tasks/test_categories.yml
tests/unit/plugins/modules/test_tag_categories.py

Changing the output of the tag module to better work with other modules, like tag_associations.
These modules benefit from using IDs instead of names, so it makes sense to provide the user with the tags identifiers as output when possible.
tags

update category outputs to include ids

---

plugins/modules/tags.py
tests/integration/targets/vmware_tags/tasks/test_tags.yml
tests/unit/plugins/modules/test_tags.py

Changing the output of the tag module to better work with other modules, like tag_associations.
These modules benefit from using IDs instead of names, so it makes sense to provide the user with the tags identifiers as output when possible.
tags

update tag output to include ids
